version: '2'
services:
  app:
    build: .
    image: chauffer/super
    environment:
      SUPER_LASTFM_API_KEY: x
    # env_file:
    #   - .env
    volumes:
      - .:/app
      - ./data:/data
    depends_on:
      - redis

  redis:
    image: redis:alpine
