version: '2'
services:
  app:
    build: .
    image: chauffer/super
    env_file:
      - .env
    volumes:
      - .:/app
      - ./data:/data
    depends_on:
      - redis

  redis:
    image: redis:alpine
